### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by mqbik** [ludo/jquery-treetable-ajax-example#10]
hi,

you should bump rails version to 4.1.2

4.1.1 do not work any more with your configuration as it depends on i18n version that is no longer in gems repositories...  don't no why..

bumping to 4.1.2 and doing bundle update solves the problem and demo works like a charm

regards,
Michal

**Comment by ludo** [comment]
Thanks for reporting! Updated bundled Rails to 4.1.7.
