### ISSUE TITLE
Plugin update problem

### ISSUE THREAD

**Issue by steveo7** [ludo/jquery-treetable-ajax-example#2]
Ludo,  Your last commit broke the example code.  I think it may have to do with the case change on treeTable to treetable in the plugin. The dynamic expanding and DD is not working.
THanks for this example anyway, it's been great for my learning.  If I figure out whats wrong, I'll post it back.

**Comment by steveo7** [comment]
I submitted a pull request.

**Comment by ludo** [comment]
Thanks for pointing this out. Fixed by steveo7 in #3.
