### ISSUE TITLE
Example not working after following information

### ISSUE THREAD

**Issue by lifejuggler** [ludo/jquery-treetable-ajax-example#4]
When I load the image into the rails 3.2 and ruby 1.9.2, I get a file explorer of what seems to be the source folder with no options to expand and only shows folders and files. Am I doing something wrong?

**Comment by ludo** [comment]
Are you using the latest version (commit c2aa4d1d93) of the example? There was an issue with the example that was fixed yesterday. Do you see something like 11 folders, or more? If you see more then there is probably an issue with the Javascript. Can you check if there are any errors?

**Comment by lifejuggler** [comment]
Yes, that was the problem its working fine now thanks!!
