### ISSUE TITLE
Backwards compatible with rails 3.0?

### ISSUE THREAD

**Issue by lifejuggler** [ludo/jquery-treetable-ajax-example#5]
I tried implementing this on rails 3.0 and was wondering if this method can also be utilized in rails 3.0 or does it only apply to 3.2 ?
Thank you

**Comment by ludo** [comment]
What part doesn't work in Rails 3.0? The code is pretty generic so it should be possible to get it to work in 3.0 as well.

**Comment by ludo** [comment]
@lifejuggler is this issue still current?

**Comment by lifejuggler** [comment]
Nope
