### ISSUE TITLE
Incompatible with jQuery version > 1.9

### ISSUE THREAD

**Issue by ycrepeau** [ludo/jquery-treetable-ajax-example#9]
$("#tree .file, #tree .directory").live("mouseenter", function()...

The jQuery "live" function has been deprecated long time ago. From version 1.9, it has been removed. 

The 'jquery-rail' gem loads version 1.11 of jQuery.

Quick fix: On the gem file, change the 'gem jquery-rail' to look:

gem 'jquery-rails', '2.1.2'

That will force rail to load an earlier version (1.8.2) version of jQuery that supports the live function.

Better fix:

Replace the 'live' function by 'on()' function. The on() call is slightly different than the live() function.

**Comment by ludo** [comment]
How do you install the gems? The bundle is already locked to jquery-rails 2.1.4 which installs jQuery 1.8.3. A `bundle install` should install the correct versions. I will update the example for Rails 4.1 anyway, thanks for the reminder :)

**Comment by ludo** [comment]
Oh and fix the `.live` deprecation of course :)

**Comment by ycrepeau** [comment]
I am new with Ruby/Rails/Gem/Bundle. I am more familiar with Cocoa (Mac OS X and iOS) development. 

So, in the process of improving my programming skills, I have created 5 or 6 test projects. In these projects I test one feature (one gem), then another feature (another gem). 

So, I could have ended up with a more recent jquery file in /vendor/xyz/assets/javascript/ or /app/assets/javascript directories. I suspect that when Rails sees "#= require jquery" in the application.coffee file, it starts looking for a jquery.js file in various locations and once it finds one, the search stops and the file is imported. I also suspect that /app/assets/javascript/_.js and /vendor/__/_.js come first in the search path and before the jquery-rails gem files. I also suspect that if another gem requires jquery before your gem is loaded and requires jquery itself, the system will load jquery just once and your gem will have a version more recent than you have expected. 

As I have said, I am a Mac Programmer. I have written software for the Mac (and the NeXT) for more than 25 years. When working on an add-on product (could be named Bundle, Component, Framework, Module, Gem etc. ), I also have these assumptions in mind:
1. The main project (the one that will receive your component) could have been in development for years. 
2. Your component is not the first to be added to that existing project. 
3. Other components will be added later in the main project development process. 
4. When the software loads, you can not assume the order when the various components are loaded. 
5. Some components will load (require) the same component but since they assume various versions of the same sub-component, incompatibilities issues will raise. 

YC

Envoyé de mon iPhone

**Comment by ludo** [comment]
> So, in the process of improving my programming skills, I have created 5 or 6 test projects. In these projects I test one feature (one gem), then another feature (another gem).
> 
> So, I could have ended up with a more recent jquery file in /vendor/xyz/assets/javascript/ or /app/assets/javascript directories.

Aha, yes, that is likely.

My (wrong) assumption was that you were referring to the standalone example project, whose bundle is already locked to a compatible version of jQuery. The ajax related JS code in the Rails views is not meant to be seen as a component, but purely to demonstrate one way to implement this functionality with the treetable plugin. However, I realize that in reality this code will be copied and expected to work out of the box. Therefore, I do consider it good practice to also keep this example up-to-date with the latest versions so I will go ahead and update it. Then we'll wait until we see an issue titled 'example not compatible with jQuery < 1.9' ;-)

I will close this issue once the code has been updated.

Merci beaucoup!
